### ISSUE TITLE
Media tab warning

### ISSUE THREAD

**Issue by tompatulpan** [YunoHost-Apps/webtrees_ynh#16]
**Describe the bug**
Going in to the "Manage Media tab" I'm getting this warning.

my.domain.do says
DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Versions**
- Hardware: computer*
- YunoHost version: 4.0.8.3
- Webtrees 2.0.10

**Comment by yalh76** [comment]
Con you try with last version ?

**Comment by tompatulpan** [comment]
All good now! 
Running version 2.1.6~ynh1
