### ISSUE TITLE
Cannot get login email for Webtrees

### ISSUE THREAD

**Issue by ralphshinevar** [YunoHost-Apps/webtrees_ynh#19]
**Versions**
- Hardware: Server hardware architecture is bare-metal amd64
  - Server model is LENOVO ThinkServer TS140
- YunoHost version: 4.1.6
- I have access to my server: *Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

Hi Yunohost webtrees.  My issue is not a bug but procedural.  My ISP is Charter Spectrum, which blocks port 25, so no email.  When I install Webtrees 2.0, it sends the password to my Yunohost email, which I cannot receive.  Can you send me a password to my gmail account (ralph.shinevar@gmail.com) so I can login?  The default for Webtrees normally is "admin" "admin" but you have modified this.  Any help would be appreciated.  Thanks.

**Comment by Thovi98** [comment]
My ISP blocks port 25 as well, but I can view my Yunohost mail. Have you already tried connecting to your Yunohost email ? 
By Thunderbird by example : https://yunohost.org/en/administrate/overview/emails/emailclients#configure-mozilla-thunderbird-on-a-desktop-computer

**Comment by ericgaspar** [comment]
#52 remove initial e-mail
