### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/webtrees_ynh#3]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/Webtrees%20(Community)/29/consoleFull

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by anmol26s** [comment]
I have updated the app to work with Yunohost 3. Hopefully Cl level will be improved.

**Comment by anmol26s** [comment]
I have fix the app.

**Comment by yalh76** [comment]
It seems that the app is still level 0 because of the error `Resource unreachable (Code 403) sous.domain.tld/path/login.php?url=index.php%3F` and a misinterpretation of the ending `%3F` by package_check the upstream app should replace `%3F` by  `?`

**Comment by toitoinebzh** [comment]
> It seems that the app is still level 0 because of the error `Resource unreachable (Code 403) sous.domain.tld/path/login.php?url=index.php%3F` and a misinterpretation of the ending `%3F` by package_check the upstream app should replace `%3F` by `?`

did you report an issue for this ?

**Comment by yalh76** [comment]
> 
> 
> > It seems that the app is still level 0 because of the error `Resource unreachable (Code 403) sous.domain.tld/path/login.php?url=index.php%3F` and a misinterpretation of the ending `%3F` by package_check the upstream app should replace `%3F` by `?`
> 
> did you report an issue for this ?

No I didn't. To let @anmol26s decide what he wants to do ^^

**Comment by maniackcrudelis** [comment]
Hi,

Your app still doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/ci/job/5580

Your app will be moved at 'notworking' status by the end of next week, on January, 4 if nothing is done before to make it work.
