### ISSUE TITLE
No initial Admin E-mail received

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/webtrees_ynh#33]
I just wanted to share my experience with an issue I had. 
I could not receive the initial e-mail after installation of Webtrees with the admin password.  It turned out that the issue was my domain that I've used (nohost.me). The Yunohost admin user is supposed to automatically send the e-mail from his account, but YH wanted to send from an e-mail alias with a domain which was not setup to work  (the initial domain that the VPS provider is using when there is no domain). 
The solution is to change the e-mail alias of the admin user to an e-mail address that is actually working and make it the default.  It took me a while to figure that out....

![grafik](https://user-images.githubusercontent.com/7679654/129920950-5abd94d5-dc02-4abc-a147-3ab54a88d9a5.png)

**Comment by ericgaspar** [comment]
#52 remove the initial e-mail
